apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-app
  labels:
    app: recipes
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recipes
  template:
    metadata:
      labels:
        app: recipes
        env: dev
    spec:
      containers:
        - name: recipes
          image: cmbrose.azurecr.io/recipes
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
