apiVersion: apps/v1
kind: Deployment
metadata:
  name: thinking-sphinx
  labels:
    app: ts
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts
  template:
    metadata:
      labels:
        app: ts
        env: dev
    spec:
      containers:
        - name: recipe
          image: cmbrose.azurecr.io/recipes
          ports:
            - name: http
              containerPort: 9306
              protocol: TCP
          env:
            - name: DB_CERT_PATH
              value: /app/BaltimoreCyberTrustRoot.crt.pem
            - name: RAILS_ENV
              value: production
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: rails-secrets
                  key: secret-key-base
