apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-app
  labels:
    app: recipes
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recipe
  template:
    metadata:
      labels:
        app: recipe
        env: dev
    spec:
      containers:
        - name: recipe
          image: cloudlifeacr.azurecr.io/k8sflask
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
