name: Deploy to AKS Cluster
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: Azure/docker-login@v1
        with:
          login-server: cmbrose.azurecr.io
          username: ${{ secrets.ACR_ADMIN_USERNAME }}
          password: ${{ secrets.ACR_ADMIN_PASSWORD }}

      - run: |
          docker build . -t cmbrose.azurecr.io/recipes:${{ github.sha }}
          docker push cmbrose.azurecr.io/recipes:${{ github.sha }}

      # Set the target AKS cluster.
      - uses: Azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: recipes-dev
          resource-group: recipes-svc-dev

      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: cmbrose.azurecr.io
          container-registry-username: ${{ secrets.ACR_ADMIN_USERNAME }}
          container-registry-password: ${{ secrets.ACR_ADMIN_PASSWORD }}
          secret-name: k8s-secret

      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            deploy/manifests/deployment.yaml
            deploy/manifests/service.yaml
          images: |
            cmbrose.azurecr.io/recipes:${{ github.sha }}
          imagepullsecrets: |
            k8s-secret
